include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    body_might_complete_normally_nullable: ignore
    camel_case_types: ignore
    constant_identifier_names: ignore
    must_be_immutable: ignore
    prefer_if_null_operators: ignore
    prefer_typing_uninitialized_variables: ignore

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
