name: dsi_pro
description: "dsi_pro is the package for quick ui and backend building with multiple method supports."

version: 0.1.9
homepage: https://devsecit.com/flutter/plugins/dsi_pro

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  http: ^1.2.0  
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  webview_flutter: ^4.10.0
  geolocator: ^13.0.1
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.devsecit.dsi_pro
        pluginClass: DSIProPlugin
        fileName: dsi_pro.dart
      ios:
        pluginClass: DSIProPlugin
        fileName: dsi_pro.dart
      macos:
        pluginClass: DSIProPlugin
        fileName: dsi_pro.dart
      web:
        pluginClass: HelloDevsecitWeb 
        fileName: dsi_pro_web.dart
      linux:
        pluginClass: DSIProPlugin
        fileName: dsi_pro.dart
      
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DSI1
      fonts:
        - asset: assets/fonts/exo/Exo2-Black.ttf
        - asset: assets/fonts/exo/Exo2-Regular.ttf 

    - family: DSI2
      fonts:
        - asset: assets/fonts/Kode/KodeMono-Bold.ttf
        - asset: assets/fonts/Kode/KodeMono-Medium.ttf
        - asset: assets/fonts/Kode/KodeMono-Regular.ttf
        - asset: assets/fonts/Kode/KodeMono-SemiBold.ttf

    - family: DSI3
      fonts:
        - asset: assets/fonts/Dance/DancingScript-Bold.ttf
        - asset: assets/fonts/Dance/DancingScript-Medium.ttf
        - asset: assets/fonts/Dance/DancingScript-Regular.ttf
        - asset: assets/fonts/Dance/DancingScript-SemiBold.ttf

    - family: DSI4
      fonts:
        - asset: assets/fonts/Noto/NotoSerif-Bold.ttf
        - asset: assets/fonts/Noto/NotoSerif-Medium.ttf
        - asset: assets/fonts/Noto/NotoSerif-Regular.ttf
        - asset: assets/fonts/Noto/NotoSerif-SemiBold.ttf

    - family: DSI5
      fonts:
        - asset: assets/fonts/Quick/Quicksand-Bold.ttf
        - asset: assets/fonts/Quick/Quicksand-Medium.ttf
        - asset: assets/fonts/Quick/Quicksand-Regular.ttf
        - asset: assets/fonts/Quick/Quicksand-SemiBold.ttf

    - family: DSI6
      fonts:
        - asset: assets/fonts/IBM/IBMPlexSans-Bold.ttf
        - asset: assets/fonts/IBM/IBMPlexSans-Medium.ttf
        - asset: assets/fonts/IBM/IBMPlexSans-Regular.ttf
        - asset: assets/fonts/IBM/IBMPlexSans-SemiBold.ttf


  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
