name: original
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dsi_pro:
    path: "./packages/dsi_pro"
  intl: ^0.18.1
  flutter_iconly: ^1.0.2
  google_fonts: ^6.2.1
  badges: ^3.1.2
  timelines: ^0.1.0
  easy_stepper: ^0.8.5
  page_transition: ^2.0.5
  image_picker: ^0.8.5+3
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.5
  pinput: ^5.0.0
  shelf: ^1.3.0
  pdf: ^3.10.4
  path_provider: ^2.0.11
  permission_handler: ^11.4.0
  printing: ^5.12.0
  shelf_router: ^1.0.0
  http: ^1.3.0
  uuid: ^4.5.1 # For generating unique OTPs
  dotenv: any
  cupertino_icons: ^1.0.8
  flutter_cashfree_pg_sdk: ^2.2.6+44
  shared_preferences: ^2.2.2
  cached_network_image: ^3.2.0
  geolocator: ^13.0.1
  geocoding: ^2.2.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon_app.png" 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/
    - assets/services/
    - assets/images/
